#!/usr/bin/bash

function print_help {
      echo "Name"
      echo "    devharbor"
      echo ""
      echo "Synopsis"
      echo "    devharbor <operation> <project-name> [options]"
      echo "    devharbor help"
      echo ""
      echo "Operations"
      echo "    init"
      echo "        Initialize a new project and create new image."
      echo "    start"
      echo "        Start or attach to container"
      echo "    remove"
      echo "        Remove project + corresponding image"
      echo ""
      echo "Init Options"
      echo "    -f"
      echo "        Specify dockerfile to use."
      echo "        From working directory      : devharbor init"
      echo "            Takes first matching 'Dockerfile' or '*.dockerfile'"
      echo "        One of the existing         : devharbor init -f arch-ruby"
      echo "        From path                   : devharbor init -f /any/path/mydockerfile.dockerfile"
      echo ""
      echo "Start Options"
      echo "    -a"
      echo "        Attach to container after starting it."
}
